version: "3"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      # nginx-proxy
      - VIRTUAL_HOST=<YOUR_VIRTUAL_HOST>
      - VIRTUAL_PORT=<YOUR_VIRTUAL_PORT>
      - LETSENCRYPT_HOST=<YOUR_LETSENCRYPT_HOST>
      - LETSENCRYPT_EMAIL=<YOUR_LETSENCRYPT_EMAIL>
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    expose:
      - "8443"
    network_mode: bridge